# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('temp_value', models.CharField(max_length=50)),
                ('temp_type', models.CharField(max_length=3)),
            ],
        ),
    ]
