# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20171008_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
