# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_window'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='pub_date',
            new_name='pubDate',
        ),
        migrations.RenameField(
            model_name='window',
            old_name='pub_date',
            new_name='pubDate',
        ),
    ]
